source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ExponentialBackOff_Example' do
  pod 'ExponentialBackOff', :path => "../"

  target 'ExponentialBackOff_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0'
    pod 'Nimble', '~> 5.1'
  end
end
