# Uncomment this line to define a global platform for your project
platform :ios, '12.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ExponentialBackOff_Example' do
  pod 'ExponentialBackOff', :path => "../"

  target 'ExponentialBackOff_Tests' do
    inherit! :search_paths
    pod 'AsyncSwift', :git => 'https://github.com/duemunk/Async.git'
    pod 'Quick', '~> 5.0'
    pod 'Nimble', '~> 10.0'
  end
end
