# Uncomment this line to define a global platform for your project
platform :ios, '12.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'ExponentialBackOff' do
  pod 'AsyncSwift', :git => 'https://github.com/duemunk/Async.git'
end

